# Generated by Django 2.0.7 on 2018-08-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluminium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='alums/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('leng', models.PositiveIntegerField(default=5800)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'clors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Color')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='aluminium',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Profile'),
        ),
        migrations.AlterIndexTogether(
            name='aluminium',
            index_together={('id', 'slug')},
        ),
    ]
